### ISSUE TITLE
Trouble starting chrome in WSL

### ISSUE THREAD

**Issue by tincann** [therealkenc/libudev-stub#1]
Hey there!
I saw your post in this [thread](https://github.com/Microsoft/BashOnWindows/issues/648) and I got excited, because now I can run js tests from WSL. However, after following the instructions in the README I'm stuck.

1. I installed libudev-stub:
```
(Reading database ... 33434 files and directories currently installed.)
Preparing to unpack ./libudev-stub-0.9.0-WSL.deb ...
Unpacking libudev-stub (0.9.0) over (0.9.0) ...
Setting up libudev-stub (0.9.0) ...
symlink libudev.so.1 -> libudev-stub.so.1
```

2. Installed the latest dev build:
```
sudo dpkg -i ./google-chrome-unstable_current_amd64.deb
```

3. Installed any missing dependencies with:
```
sudo apt -f install
```

4. And finally, tried to run chrome, but this unfortunately results in the following:
```
~  google-chrome --version
Google Chrome 60.0.3080.5 dev
~  google-chrome-unstable --no-sandbox
[1]    7275 trace trap (core dumped)  google-chrome-unstable --no-sandbox
~  google-chrome --no-sandbox
[1]    7286 trace trap (core dumped)  google-chrome --no-sandbox
```

**Comment by therealkenc** [comment]
The symlink seems to get blown away by `apt` really easily. That's usually the problem if you get a trap right out of the gate. Do `ls -l /lib/x86_64-linux-gnu/libudev*` and you should see something like below (scroll right to see the full link). Just run `dpkg -i` again and it should fix up the symlink.

If that doesn't work, make sure other X11 apps are working (`xeyes`, `firefox`) and we can try to figure the problem further from there.
```
$ ls -l /lib/x86_64-linux-gnu/libudev*
lrwxrwxrwx 1 root root     39 May  3 08:27 /lib/x86_64-linux-gnu/libudev.so.1 -> /lib/x86_64-linux-gnu/libudev-stub.so.1
-rw-r--r-- 1 root root 126840 Feb 15 07:11 /lib/x86_64-linux-gnu/libudev.so.1.6.4
lrwxrwxrwx 1 root root     17 Mar  4 19:40 /lib/x86_64-linux-gnu/libudev-stub.so -> libudev-stub.so.1
lrwxrwxrwx 1 root root     21 Mar  4 19:40 /lib/x86_64-linux-gnu/libudev-stub.so.1 -> libudev-stub.so.1.6.4
-rw-r--r-- 1 root root  66560 Mar  4 17:45 /lib/x86_64-linux-gnu/libudev-stub.so.1.6.4
```

**Comment by tincann** [comment]
I'm going to try your suggestion and report back next week when I have access to the Windows machine again.

Thank you for the help and quick response.

**Comment by tincann** [comment]
I saw you updated your README. Therefore, I tried it again with these commands added:
```
wget https://github.com/therealkenc/libudev-stub/releases/download/v0.9.0/libpulse0_8.0-0ubuntu3.2ppa1_amd64.deb
sudo dpkg -i libpulse0_8.0-0ubuntu3.2ppa1_amd64.deb
sudo apt -f install
```

The symlink seems to be present.
```
➜  ~ ls -l /lib/x86_64-linux-gnu/libudev*
lrwxrwxrwx 1 root root    39 May 10 11:08 /lib/x86_64-linux-gnu/libudev.so.1 -> /lib/x86_64-linux-gnu/libudev-stub.so.1
-rw-r--r-- 1 root root 67600 Feb  7 12:06 /lib/x86_64-linux-gnu/libudev.so.1.3.5
lrwxrwxrwx 1 root root    17 Mar  5 04:40 /lib/x86_64-linux-gnu/libudev-stub.so -> libudev-stub.so.1
lrwxrwxrwx 1 root root    21 Mar  5 04:40 /lib/x86_64-linux-gnu/libudev-stub.so.1 -> libudev-stub.so.1.6.4
-rw-r--r-- 1 root root 66560 Mar  5 02:45 /lib/x86_64-linux-gnu/libudev-stub.so.1.6.4
```
Doesn't work unfortunately.
```
➜  ~ google-chrome --no-sandbox
[1]    1845 trace trap (core dumped)  google-chrome --no-sandbox
```

Looks like the other applications aren't working either.
```
➜  ~ xeyes
Error: Can't open display:
➜  ~ firefox
Sandbox: unexpected multithreading found; this prevents using namespace sandboxing.
Error: GDK_BACKEND does not match available displays
```

**Comment by therealkenc** [comment]
Having firefox etc working is kind of a prerequisite to jumping into the Chrome deep end. Wild guess `export DISPLAY=locahost:0`.
