### ISSUE TITLE
Please do not take this library down

### ISSUE THREAD

**Issue by 418tea** [therealkenc/libudev-stub#2]
From the language of the project's README, it can be inferred that you are going to take the project down. Please do not do so. This stub library has proven very useful to me, since I use it to get software that requires udev to run under termux (https://termux.com/), a linux environment and terminal emulator for android. So, you could either keep working on this library with this goal in mind, or leave it as is, if you want to. Just don't take it down! :slightly_smiling_face:

**Comment by therealkenc** [comment]
Sure no problem. There's lots more that could be done with the stub/proxy in principle; I just didn't think anyone was using it. If it is useful for even one person that's great. Thanks for dropping by.
