### ISSUE TITLE
Getting UDEV STUB: Using libudev-stub 0.9.0

### ISSUE THREAD

**Issue by Kblipz** [therealkenc/libudev-stub#3]
After I followed these steps: https://github.com/Microsoft/WSL/issues/648#issuecomment-284205244
 
I am getting this error `UDEV STUB: Using libudev-stub 0.9.0` whenever I execute any command.

For example, if I execute a invalid command like:

```
~$ vdrfvrf
UDEV STUB: Using libudev-stub 0.9.0
vdrfvrf: command not found
```
I am getting this `UDEV STUB: Using libudev-stub 0.9.0` with almost every command even with apt.

**Comment by therealkenc** [comment]
If you are getting that message out of _every_ command (even ones that are not found) it means you have put something on your system that is loading `libudev` every command. Which would be real unusual, bordering on broken. The logging was intended just for the purposes of knowing that you had `libdev-stub` (and not the real thing) when starting something exceptional like Chrome.

In any case I pushed a deb that makes the logging opt-in. Note I haven't even run the new (scare quote) "release" once, but it was a five min change so why not. That will quash the noise, but if something on your system is looking for a functioning `libudev` every time you type `ls`, and that something is expecting a working `udev`, that something is probably going to be disappointed. Bonne chance.

**Comment by azaeng04** [comment]
@therealkenc how can we undo the install of the libudev package? It also gives me that error.

**Comment by therealkenc** [comment]
Same as every `.deb`. Or just "`sudo apt install --reinstall udev libudev1`". In fact, per commentary in the README, it's hard to **not** undo the install of `libudev-stub`; just about any `apt install` involving `udev` blows it away.

[ed: Noting that, whether you blow away `libudev-stub` or not, if you are getting that message out of _every_ command you run, your setup is pretty hooped, entirely independent of `libudev-stub`. Reinstalling `udev` is just masking the problem with your rig. Granted being comfortably oblivious is better than an annoying debug message I suppose.]

**Comment by azaeng04** [comment]
@therealkenc I think you are forgetting that any apt-get or apt just does not work. It is okay I just deleted the distribution with the error on it and started a new one.

**Comment by therealkenc** [comment]
You did not mention that `apt` does not work, only that you got (quoth) "that error" from the OP when a command was not found (a command like`vdrfvrf`). 

In your case what couldn't be found was `apt`, and possibly much else. Probably due to a `$PATH` problem. 

Starting over is always a good big hammer fix when available.

**Comment by ericblade** [comment]
````
E: Invalid message from method http: UDEV STUB: Using libudev-stub 0.9.0
   100 Capabilities
   Send-Config: true
   Version: 1.2
   Pipeline: true
````

I've been using WSL fine for months, this came up today when I tried to apt-get update then install something... 

edit: using your ```sudo apt install --reinstall udev libudev1``` reinstalled the standard udev from cache, and now i'm back to normal.

**Comment by dannywamuya** [comment]
I'm new to programming and I have been using WSL for about a month now. I'm trying to install nodejs using `nvm install <version>`.
Whenever I do that or even ran apt commands I get a  `UDEV STUB: Using libudev-stub 0.9.0` and it suggests `sudo apt install <deb name>`
I'm not sure what's wrong with my setup but would appreciate help with this.

I also ran `sudo apt install --reinstall udev libudev1` and this is what it returned 

`E: Invalid message from method http: UDEV STUB: Using libudev-stub 0.9.0
   100 Capabilities
   Send-Config: true
   Version: 1.2
   Pipeline: true`

![libudev](https://user-images.githubusercontent.com/55041781/93370923-377e7180-f85a-11ea-9591-287904a2249a.png)

**Comment by therealkenc** [comment]
Restore the stock libudev per #4.
