### ISSUE TITLE
Unable to remove libudev-stub from WSL

### ISSUE THREAD

**Issue by rickynyairo** [therealkenc/libudev-stub#4]
I am currently unable to remove libudev-stub after installing it 
I did:
`
sudo apt install ./libudev-stub-0.9.0-WSL.deb
`
However, after removing it using:
`
sudo dpkg -r libudev-stub
`

Now all my attempts at using apt : apt intsall, apt-get update are returning the error message:
`
error while loading shared libraries: libudev.so.1: cannot open shared object file: No such file or directory
`
What can I do to remove the library and restore WSL to its original state?
@therealkenc

**Comment by therealkenc** [comment]
`sudo apt install --reinstall udev libudev1` will probably get you there.

**Comment by rickynyairo** [comment]
I've done that. 
However, I'm getting the following message on every apt install:
```
UDEV STUB: Using libudev-stub 0.9.0
apt: /lib/x86_64-linux-gnu/libudev.so.1: no version information available (required by /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0)
UDEV STUB: Using libudev-stub 0.9.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcanberra0 libstartup-notification0 libtdb1 libxcb-util1 sound-theme-freedesktop xul-ext-ubufox
Suggested packages:
  fonts-lyx libcanberra-gtk0 libcanberra-pulse
/usr/lib/apt/methods/http: /lib/x86_64-linux-gnu/libudev.so.1: no version information available (required by /usr/lib/x86_64-linux-gnu/libapt-pkg.so.5.0)
E: Invalid message from method http: UDEV STUB: Using libudev-stub 0.9.0
   100 Capabilities
   Send-Config: true
   Version: 1.2
   Pipeline: true
```

**Comment by therealkenc** [comment]
This might work:
```
sudo ln -fs /lib/x86_64-linux-gnu/libudev.so.1.6.9 /lib/x86_64-linux-gnu/libudev.so.1
```

Check your stock `libudev` version number first with `ls -l /lib/x86_64-linux-gnu/libudev*`. It might not be `1.6.9`, that depends on your disto.

**Comment by rickynyairo** [comment]
I ended up reinstalling/resetting WSL. Probably my own fault for messing it up

**Comment by therealkenc** [comment]
Thanks for the submission regardless. I don't think much of anyone has done an `sudo dpkg -r libudev-stub`. The [postinst](https://github.com/therealkenc/libudev-stub/blob/master/scripts/postinst) just sets up one symbolic link. Uninstalling amounts to restoring the symlink. The project was just to get Chrome up on early WSL1, where `udev` won't work whether this stub is installed or not.

**Comment by dirathea** [comment]
I can confirm that [this steps](https://github.com/therealkenc/libudev-stub/issues/4#issuecomment-592202766) really do fix the issue.

I also got messed up when trying to run google chrome on wsl, and broke my apt-get.

What I do as follows : 

```
➜ ls -l /lib/x86_64-linux-gnu/libudev*
lrwxrwxrwx 1 root root     17 Mar  5  2017 /lib/x86_64-linux-gnu/libudev-stub.so -> libudev-stub.so.1
lrwxrwxrwx 1 root root     21 Mar  5  2017 /lib/x86_64-linux-gnu/libudev-stub.so.1 -> libudev-stub.so.1.6.4
-rw-r--r-- 1 root root  66560 Mar  5  2017 /lib/x86_64-linux-gnu/libudev-stub.so.1.6.4
lrwxrwxrwx 1 root root     38 Aug 25 20:19 /lib/x86_64-linux-gnu/libudev.so.1 -> /lib/x86_64-linux-gnu/libudev.so.1.6.9
-rw-r--r-- 1 root root 174272 Apr 22 16:04 /lib/x86_64-linux-gnu/libudev.so.1.6.17
```

Then do the symlink

```
sudo ln -fs /lib/x86_64-linux-gnu/libudev.so.1.6.17 /lib/x86_64-linux-gnu/libudev.so.1
```

**Comment by sachin3973** [comment]
Thanks it just fixed everything. 👍

**Comment by seenickcode** [comment]
The solution worked except for some reason I didn't even have `libudev.so.1.6.9`, so I had to first download the .deb package [here](https://ubuntu.pkgs.org/18.04/ubuntu-main-amd64/libudev1_237-3ubuntu10_amd64.deb.html) using wget, then run `sudo dpkg -i <downloaded file.deb>`, then run the `ln -fs` command cited in the solution above and it worked.
